language: php
php:
  - '7.1'
  - '7.2'
  # PHP 7.3 does not work yet, the following error occurs:
  #   ErrorException: Invalid argument supplied for foreach()
  #   /home/travis/build/francescozanoni/students-api-php/vendor/illuminate/support/Arr.php:582
  #   /home/travis/build/francescozanoni/students-api-php/vendor/illuminate/support/helpers.php:302
  #   /home/travis/build/francescozanoni/students-api-php/tests/TestCase.php:44
  #   /home/travis/build/francescozanoni/students-api-php/tests/AnnotationsTest.php:539
  #  - '7.3'
install:
  - composer install
  - php scripts/setup.php
  - php artisan openapi:configure
script: php vendor/bin/phpunit tests --coverage-clover storage/clover.xml
after_success:
  - travis_retry php vendor/bin/php-coveralls --coverage_clover=storage/clover.xml